/* Shared PPLUL concept from the native catalogs. Each option is ranked best-first. */
(() => {
  const t=(en,fi)=>({en,fi});
  const slot=(id,role,reps,options)=>({id,role:t(...role),reps,options:options.map(x=>t(...x))});
  const push=[
    slot('upper_chest',['Upper-chest press','Ylärinnan punnerrus'],'6–10', [['Smith-machine incline press','Smith-vinopenkki'],['Plate-loaded incline press','Levypainollinen vinopenkkikone'],['Incline dumbbell press','Käsipainovinopenkki'],['Low-incline barbell press','Loiva vinopenkki tangolla'],['Single-arm cable press','Yhden käden taljapunnerrus']]),
    slot('shoulder_press',['Shoulder press','Olkapääpunnerrus'],'6–10', [['Machine shoulder press','Olkapääpunnerrus koneessa'],['Smith shoulder press','Smith-olkapääpunnerrus'],['Seated dumbbell press','Istuen käsipainopunnerrus'],['High-incline machine press','Jyrkkä vinopenkkipunnerrus koneessa'],['Landmine press','Landmine-punnerrus']]),
    slot('chest_isolation',['Chest isolation','Rinnan eristävä liike'],'10–15', [['Cable fly (lengthened bias)','Taljaflyes venytyspainotteisesti'],['Pec-deck fly','Pec deck -flyes'],['Bayesian cable fly','Bayesian-taljaflyes'],['Dumbbell fly (controlled)','Hallittu käsipainoflyes'],['Push-up on handles','Punnerrus kahvoilla']]),
    slot('lateral_delts',['Lateral delts','Sivuhartiat'],'10–20', [['Cable lateral raise','Vipunosto sivulle taljassa'],['Machine lateral raise','Vipunosto sivulle koneessa'],['Lean-away cable raise','Nojaava taljavipunosto'],['Dumbbell lateral raise','Vipunosto sivulle käsipainoilla'],['Incline bench lateral raise','Vipunosto sivulle vinopenkillä']]),
    slot('triceps_long',['Triceps long head','Ojentajan pitkä pää'],'8–15', [['Overhead cable extension','Ojentajapunnerrus pään yli taljassa'],['Single-arm overhead cable extension','Yhden käden ojentajapunnerrus pään yli'],['EZ-bar overhead extension','EZ-tangon ojentajapunnerrus pään yli'],['Dumbbell overhead extension','Käsipainon ojentajapunnerrus pään yli'],['Incline cable skull crusher','Taljaskull crusher vinopenkillä']]),
    slot('triceps_pressdown',['Triceps pressdown','Ojentajapunnerrus'],'8–15', [['Cable pressdown','Ojentajapunnerrus taljassa'],['Single-arm cable pressdown','Yhden käden ojentajapunnerrus taljassa'],['V-bar pressdown','V-kahvan ojentajapunnerrus'],['Assisted dip','Avustettu dippi'],['Close-grip push-up','Kapea punnerrus']])
  ];
  const pull=[
    slot('vertical_pull',['Vertical pull','Pystysuuntainen veto'],'6–12', [['Neutral-grip pulldown','Neutraali ylätalja'],['Assisted neutral-grip pull-up','Avustettu neutraali leuanveto'],['Single-arm lat pulldown','Yhden käden ylätalja'],['Pronated pulldown','Myötäotteinen ylätalja'],['Chin-up','Vastaoteleuanveto']]),
    slot('upper_back_row',['Upper-back row','Yläselkäsoutu'],'6–12', [['Chest-supported wide row','Rintatuettu leveä soutu'],['Plate-loaded upper-back row','Levypainollinen yläselkäsoutu'],['Seal row','Seal row'],['Cable high row','Korkea taljasoutu'],['Wide-grip machine row','Leveä soutu koneessa']]),
    slot('lat_row',['Lat-focused row','Leveään selkälihakseen painottuva soutu'],'8–15', [['Single-arm cable lat row','Yhden käden lat-soutu taljassa'],['Chest-supported close row','Rintatuettu kapea soutu'],['Machine low row','Matala soutu koneessa'],['Dumbbell lat row','Käsipainosoutu lat-painotuksella'],['Straight-arm pulldown','Suorin käsin ylätaljaveto']]),
    slot('rear_delts',['Rear delts','Takahartiat'],'10–20', [['Reverse pec deck','Käänteinen pec deck'],['Cable rear-delt fly','Takahartiaflyes taljassa'],['Chest-supported rear-delt row','Rintatuettu takahartiasoutu'],['Single-arm cable rear fly','Yhden käden takahartiaflyes taljassa'],['Bent-over dumbbell raise','Kumartunut vipunosto käsipainoilla']]),
    slot('lengthened_biceps',['Lengthened biceps','Hauis venytyspainotteisesti'],'8–15', [['Bayesian cable curl','Bayesian-taljahauiskääntö'],['Incline dumbbell curl','Hauiskääntö vinopenkillä'],['Behind-body cable curl','Taljahauiskääntö vartalon takaa'],['Preacher curl','Scott-hauiskääntö'],['Alternating dumbbell curl','Vuorottainen käsipainohauiskääntö']]),
    slot('neutral_curl',['Brachialis / neutral curl','Brachialis / neutraali hauiskääntö'],'8–15', [['Rope hammer curl','Köysivasarakääntö'],['Cross-body hammer curl','Vasarakääntö vartalon poikki'],['Machine neutral curl','Neutraali hauiskääntö koneessa'],['Dumbbell hammer curl','Vasarakääntö käsipainoilla'],['Reverse EZ-bar curl','Käänteinen EZ-hauiskääntö']])
  ];
  const lower=(variant)=>[
    slot(`quad_${variant}`,['Quad compound','Etureisien moninivelliike'],'6–10', variant==='lower' ? [['Pendulum squat','Pendulum-kyykky'],['Hack squat','Hack-kyykky'],['Smith squat (heels elevated)','Smith-kyykky kantapäät korotettuna'],['Belt squat','Vyökyykky'],['High-bar squat','Korkea takakyykky']] : [['Hack squat','Hack-kyykky'],['Pendulum squat','Pendulum-kyykky'],['Smith squat (heels elevated)','Smith-kyykky kantapäät korotettuna'],['High-bar squat','Korkea takakyykky'],['Belt squat','Vyökyykky']]),
    slot(`hinge_${variant}`,['Hip hinge / glutes','Lantionojennus / pakarat'],'6–10', [['Romanian deadlift','Romanialainen maastaveto'],['Smith Romanian deadlift','Romanialainen maastaveto Smithissä'],['Hip thrust machine','Lantionnosto koneessa'],['Barbell hip thrust','Lantionnosto tangolla'],['45-degree back extension','45 asteen selänojennus']]),
    slot(`single_${variant}`, variant==='lower'?['Unilateral legs','Yhden jalan liike']:['Leg press pattern','Jalkaprässiliike'],'8–15', variant==='lower' ? [['Bulgarian split squat','Bulgarialainen askelkyykky'],['Reverse lunge (Smith)','Peruutusaskelkyykky Smithissä'],['Step-up','Korokkeelle nousu'],['Single-leg press','Yhden jalan jalkaprässi'],['Walking lunge','Kävelyaskelkyykky']] : [['Leg press (deep ROM)','Jalkaprässi syvällä liikeradalla'],['Single-leg press','Yhden jalan jalkaprässi'],['Machine squat','Kyykky koneessa'],['Front squat','Etukyykky'],['Goblet squat (heels elevated)','Goblet-kyykky kantapäät korotettuna']]),
    slot(`curl_${variant}`,['Knee flexion','Polven koukistus'],'8–15', [['Seated leg curl','Reidenkoukistus istuen'],['Lying leg curl','Reidenkoukistus maaten'],['Single-leg seated curl','Yhden jalan reidenkoukistus istuen'],['Nordic curl (assisted)','Avustettu Nordic curl'],['Stability-ball leg curl','Reidenkoukistus jumppapallolla']]),
    slot(`extension_${variant}`,['Knee extension','Polven ojennus'],'10–20', [['Leg extension','Reidenojennus'],['Single-leg extension','Yhden jalan reidenojennus'],['Sissy squat (assisted)','Avustettu sissy-kyykky'],['Reverse Nordic curl','Käänteinen Nordic curl'],['Spanish squat','Spanish squat']]),
    slot(`calves_${variant}`,['Calves','Pohkeet'],'8–15', variant==='lower' ? [['Seated calf raise','Pohjenousu istuen'],['Standing calf raise','Pohjenousu seisten'],['Leg-press calf raise','Pohjenousu jalkaprässissä'],['Smith standing calf raise','Pohjenousu seisten Smithissä'],['Single-leg calf raise','Yhden jalan pohjenousu']] : [['Standing calf raise','Pohjenousu seisten'],['Leg-press calf raise','Pohjenousu jalkaprässissä'],['Smith standing calf raise','Pohjenousu seisten Smithissä'],['Seated calf raise','Pohjenousu istuen'],['Single-leg calf raise','Yhden jalan pohjenousu']])
  ];
  const legs=lower('legs'); const lowerDay=lower('lower');
  const upper=[
    slot('chest_press',['Chest press','Rintapunnerrus'],'6–10', [['Plate-loaded chest press','Levypainollinen rintapunnerrus'],['Smith incline press','Smith-vinopenkki'],['Machine chest press','Rintapunnerrus koneessa'],['Incline dumbbell press','Käsipainovinopenkki'],['Barbell bench press','Penkkipunnerrus tangolla']]),
    pull[1],pull[0],push[1],push[3],
    slot('upper_biceps',['Biceps','Hauikset'],'8–15', [['Bayesian cable curl','Bayesian-taljahauiskääntö'],['Preacher curl','Scott-hauiskääntö'],['Incline dumbbell curl','Hauiskääntö vinopenkillä'],['Cable curl','Hauiskääntö taljassa'],['EZ-bar curl','EZ-tankohauiskääntö']]),
    slot('upper_triceps',['Triceps','Ojentajat'],'8–15', [['Overhead cable extension','Ojentajapunnerrus pään yli taljassa'],['Single-arm overhead extension','Yhden käden ojentajapunnerrus pään yli'],['Cable pressdown','Ojentajapunnerrus taljassa'],['Machine dip','Dippi koneessa'],['EZ-bar skull crusher','EZ-tangon skull crusher']])
  ];
  const day=(id,en,fi,slots)=>({id,name:t(en,fi),slots});
  const base={push:day('push','Push','Työntävät',push),pull:day('pull','Pull','Vetävät',pull),legs:day('legs','Legs','Jalat',legs),upper:day('upper','Upper','Ylävartalo',upper),lower:day('lower','Lower','Alavartalo',lowerDay)};
  window.RT_PROGRAMS={
    pplul:{name:t('Push · Pull · Legs · Upper · Lower','Työntävät · Vetävät · Jalat · Ylävartalo · Alavartalo'),days:5,activity:.055,protein:.15,plan:[base.push,base.pull,base.legs,base.upper,base.lower]},
    upperLower:{name:t('Upper / Lower','Ylä- / alavartalo'),days:4,activity:.04,protein:.10,plan:[base.upper,base.lower,base.upper,base.lower]},
    fullBody:{name:t('Full Body','Koko vartalo'),days:3,activity:.025,protein:.05,plan:[day('fullA','Full Body A','Koko vartalo A',[push[0],pull[0],legs[0],legs[3],push[3],legs[5]]),day('fullB','Full Body B','Koko vartalo B',[upper[0],upper[1],lowerDay[1],lowerDay[2],upper[5],upper[6]]),day('fullC','Full Body C','Koko vartalo C',[push[2],pull[2],legs[2],legs[4],pull[3],lowerDay[5]])]},
    recovery:{name:t('Active Recovery','Aktiivinen palautuminen'),days:2,activity:0,protein:0,plan:[day('mobility','Mobility','Liikkuvuus',legs.slice(0,3)),day('technique','Technique','Tekniikka',[push[0],pull[0],legs[0]])]}
  };
})();
